<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ExpertTradersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $experts = [
            [
                'name' => 'Michael Chen',
                'avatar' => 'https://i.pravatar.cc/300?img=12',
                'total_followers' => 2847,
                'roi_percentage' => 156.80,
                'total_trades' => 1523,
                'win_rate' => 78.50,
                'total_pnl' => 284500.00,
                'portfolio_value' => 500000.00,
                'risk_score' => 6.0,
                'experience_years' => 8,
                'specialization' => 'Cryptocurrency',
                'status' => 'active',
                'subscription_fee' => 99.00,
                'performance_fee' => 15.00,
                'min_copy_amount' => 500.00,
                'max_copy_amount' => 50000.00,
                'description' => 'Professional cryptocurrency trader with 8+ years of experience. Specialized in technical analysis and swing trading strategies. Former hedge fund manager.',
                'trading_strategy' => 'Technical Analysis & Swing Trading - Using advanced chart patterns, support/resistance levels, and momentum indicators to identify high-probability trade setups.',
                'last_active_at' => Carbon::now(),
                'created_at' => Carbon::now()->subMonths(24),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sarah Williams',
                'avatar' => 'https://i.pravatar.cc/300?img=47',
                'total_followers' => 1965,
                'roi_percentage' => 142.60,
                'total_trades' => 2341,
                'win_rate' => 82.30,
                'total_pnl' => 198750.00,
                'portfolio_value' => 350000.00,
                'risk_score' => 4.0,
                'experience_years' => 6,
                'specialization' => 'Forex & Crypto',
                'status' => 'active',
                'subscription_fee' => 79.00,
                'performance_fee' => 12.00,
                'min_copy_amount' => 300.00,
                'max_copy_amount' => 30000.00,
                'description' => 'Elite forex and crypto trader. Focused on scalping and day trading with consistent returns. Risk management expert.',
                'trading_strategy' => 'Scalping & Day Trading - Quick entries and exits with strict risk management. Multiple small wins throughout the day.',
                'last_active_at' => Carbon::now()->subMinutes(15),
                'created_at' => Carbon::now()->subMonths(18),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alexander Petrov',
                'avatar' => 'https://i.pravatar.cc/300?img=33',
                'total_followers' => 3241,
                'roi_percentage' => 189.40,
                'total_trades' => 4567,
                'win_rate' => 75.80,
                'total_pnl' => 456890.00,
                'portfolio_value' => 750000.00,
                'risk_score' => 7.0,
                'experience_years' => 10,
                'specialization' => 'Algorithmic Trading',
                'status' => 'active',
                'subscription_fee' => 149.00,
                'performance_fee' => 18.00,
                'min_copy_amount' => 1000.00,
                'max_copy_amount' => 100000.00,
                'description' => 'Quantitative trader using algorithmic strategies. PhD in Financial Engineering. Specializes in high-frequency trading and market making.',
                'trading_strategy' => 'Algorithmic High-Frequency Trading - Automated systems executing hundreds of trades daily based on mathematical models and market inefficiencies.',
                'last_active_at' => Carbon::now()->subMinutes(5),
                'created_at' => Carbon::now()->subMonths(30),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emma Thompson',
                'avatar' => 'https://i.pravatar.cc/300?img=45',
                'total_followers' => 1523,
                'roi_percentage' => 98.50,
                'total_trades' => 892,
                'win_rate' => 71.20,
                'total_pnl' => 167400.00,
                'portfolio_value' => 280000.00,
                'risk_score' => 3.0,
                'experience_years' => 5,
                'specialization' => 'Long-term Investing',
                'status' => 'active',
                'subscription_fee' => 59.00,
                'performance_fee' => 10.00,
                'min_copy_amount' => 250.00,
                'max_copy_amount' => 25000.00,
                'description' => 'Long-term trend following specialist. Conservative approach with steady growth. Perfect for risk-averse investors.',
                'trading_strategy' => 'Trend Following & Position Trading - Holding positions for weeks or months, riding major market trends with patience and discipline.',
                'last_active_at' => Carbon::now()->subHours(2),
                'created_at' => Carbon::now()->subMonths(15),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Carlos Rodriguez',
                'avatar' => 'https://i.pravatar.cc/300?img=15',
                'total_followers' => 2156,
                'roi_percentage' => 234.70,
                'total_trades' => 1876,
                'win_rate' => 69.40,
                'total_pnl' => 328900.00,
                'portfolio_value' => 420000.00,
                'risk_score' => 8.0,
                'experience_years' => 4,
                'specialization' => 'DeFi & Altcoins',
                'status' => 'active',
                'subscription_fee' => 119.00,
                'performance_fee' => 20.00,
                'min_copy_amount' => 500.00,
                'max_copy_amount' => 40000.00,
                'description' => 'DeFi and altcoin expert. Early adopter with a keen eye for emerging projects. High risk, high reward strategy.',
                'trading_strategy' => 'DeFi & Altcoin Speculation - Identifying undervalued altcoins and DeFi projects before they gain mainstream attention.',
                'last_active_at' => Carbon::now()->subMinutes(30),
                'created_at' => Carbon::now()->subMonths(12),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Yuki Tanaka',
                'avatar' => 'https://i.pravatar.cc/300?img=52',
                'total_followers' => 1789,
                'roi_percentage' => 128.30,
                'total_trades' => 1654,
                'win_rate' => 76.90,
                'total_pnl' => 215600.00,
                'portfolio_value' => 380000.00,
                'risk_score' => 5.0,
                'experience_years' => 7,
                'specialization' => 'Asian Markets',
                'status' => 'active',
                'subscription_fee' => 89.00,
                'performance_fee' => 14.00,
                'min_copy_amount' => 400.00,
                'max_copy_amount' => 35000.00,
                'description' => 'Asian market specialist focusing on Japanese and Korean crypto markets. News-driven trader with fast execution.',
                'trading_strategy' => 'News Trading & Market Sentiment - Capitalizing on breaking news and social media sentiment to capture quick price movements.',
                'last_active_at' => Carbon::now()->subHours(1),
                'created_at' => Carbon::now()->subMonths(20),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David Anderson',
                'avatar' => 'https://i.pravatar.cc/300?img=68',
                'total_followers' => 2634,
                'roi_percentage' => 167.20,
                'total_trades' => 1234,
                'win_rate' => 73.60,
                'total_pnl' => 267800.00,
                'portfolio_value' => 550000.00,
                'risk_score' => 6.0,
                'experience_years' => 6,
                'specialization' => 'On-Chain Analysis',
                'status' => 'active',
                'subscription_fee' => 109.00,
                'performance_fee' => 16.00,
                'min_copy_amount' => 600.00,
                'max_copy_amount' => 60000.00,
                'description' => 'Blockchain analyst and whale tracker. Uses on-chain data and whale movements to predict market trends.',
                'trading_strategy' => 'On-Chain Analysis & Whale Tracking - Following smart money movements and analyzing blockchain metrics for trade signals.',
                'last_active_at' => Carbon::now()->subMinutes(20),
                'created_at' => Carbon::now()->subMonths(16),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Priya Sharma',
                'avatar' => 'https://i.pravatar.cc/300?img=40',
                'total_followers' => 1892,
                'roi_percentage' => 145.80,
                'total_trades' => 1456,
                'win_rate' => 80.10,
                'total_pnl' => 234500.00,
                'portfolio_value' => 410000.00,
                'risk_score' => 5.0,
                'experience_years' => 9,
                'specialization' => 'Institutional Trading',
                'status' => 'active',
                'subscription_fee' => 94.00,
                'performance_fee' => 13.00,
                'min_copy_amount' => 500.00,
                'max_copy_amount' => 45000.00,
                'description' => 'Smart money concepts trader. Former investment banker with expertise in institutional trading strategies.',
                'trading_strategy' => 'Smart Money Concepts & Order Flow - Reading institutional order flow and following the footsteps of major market players.',
                'last_active_at' => Carbon::now()->subMinutes(45),
                'created_at' => Carbon::now()->subMonths(22),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Marcus Weber',
                'avatar' => 'https://i.pravatar.cc/300?img=56',
                'total_followers' => 2103,
                'roi_percentage' => 112.90,
                'total_trades' => 1789,
                'win_rate' => 77.30,
                'total_pnl' => 189400.00,
                'portfolio_value' => 320000.00,
                'risk_score' => 4.0,
                'experience_years' => 8,
                'specialization' => 'Systematic Trading',
                'status' => 'active',
                'subscription_fee' => 69.00,
                'performance_fee' => 11.00,
                'min_copy_amount' => 350.00,
                'max_copy_amount' => 28000.00,
                'description' => 'Systematic trader with military precision. Rule-based trading with strict risk management protocols.',
                'trading_strategy' => 'Systematic Rule-Based Trading - Following proven algorithms with no emotional interference. Discipline is key.',
                'last_active_at' => Carbon::now()->subHours(3),
                'created_at' => Carbon::now()->subMonths(19),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Isabella Costa',
                'avatar' => 'https://i.pravatar.cc/300?img=44',
                'total_followers' => 2487,
                'roi_percentage' => 198.60,
                'total_trades' => 2145,
                'win_rate' => 68.50,
                'total_pnl' => 312700.00,
                'portfolio_value' => 460000.00,
                'risk_score' => 7.0,
                'experience_years' => 5,
                'specialization' => 'Momentum Trading',
                'status' => 'active',
                'subscription_fee' => 114.00,
                'performance_fee' => 17.00,
                'min_copy_amount' => 450.00,
                'max_copy_amount' => 38000.00,
                'description' => 'Momentum and breakout specialist. Catches explosive moves in volatile markets with precision timing.',
                'trading_strategy' => 'Momentum Trading & Breakouts - Identifying strong momentum and entering before breakouts for maximum profit potential.',
                'last_active_at' => Carbon::now()->subMinutes(10),
                'created_at' => Carbon::now()->subMonths(14),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'James Mitchell',
                'avatar' => 'https://i.pravatar.cc/300?img=13',
                'total_followers' => 1678,
                'roi_percentage' => 156.40,
                'total_trades' => 1567,
                'win_rate' => 74.20,
                'total_pnl' => 245800.00,
                'portfolio_value' => 390000.00,
                'risk_score' => 6.0,
                'experience_years' => 7,
                'specialization' => 'Volatility Trading',
                'status' => 'active',
                'subscription_fee' => 99.00,
                'performance_fee' => 15.00,
                'min_copy_amount' => 550.00,
                'max_copy_amount' => 55000.00,
                'description' => 'Volatility trading expert. Options and futures background. Profits from market uncertainty.',
                'trading_strategy' => 'Volatility Trading & Options - Exploiting market volatility through strategic options positions and futures hedging.',
                'last_active_at' => Carbon::now()->subMinutes(25),
                'created_at' => Carbon::now()->subMonths(17),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sophie Laurent',
                'avatar' => 'https://i.pravatar.cc/300?img=48',
                'total_followers' => 1456,
                'roi_percentage' => 108.70,
                'total_trades' => 987,
                'win_rate' => 79.60,
                'total_pnl' => 178900.00,
                'portfolio_value' => 295000.00,
                'risk_score' => 3.0,
                'experience_years' => 6,
                'specialization' => 'Value Investing',
                'status' => 'active',
                'subscription_fee' => 74.00,
                'performance_fee' => 12.00,
                'min_copy_amount' => 300.00,
                'max_copy_amount' => 32000.00,
                'description' => 'European markets specialist with a focus on fundamental analysis. Long-term value investor in crypto space.',
                'trading_strategy' => 'Fundamental Analysis & Value Investing - Deep research into project fundamentals, team, and long-term potential.',
                'last_active_at' => Carbon::now()->subHours(4),
                'created_at' => Carbon::now()->subMonths(13),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($experts as $expert) {
            DB::table('expert_traders')->insert($expert);
        }

        $this->command->info('✅ Successfully created 12 expert traders!');
    }
}
