@extends('emails.layout')

@section('content')
<h1>🎉 New Profit Generated!</h1>

<p>Hello {{ $user->name }},</p>
<p>Congratulations! Your trading bot has generated a new return on your investment. Your profits have been automatically credited to your account.</p>

<div class="success-box">
    <p><strong>Profit Credited!</strong> Your earnings are now available in your account.</p>
</div>

<h2>Profit Details</h2>

<table class="details-table">
    <tr>
        <td>Trading Bot</td>
        <td>{{ $plan }}</td>
    </tr>
    <tr>
        <td>Profit Amount</td>
        <td>{{ $user->currency }}{{ number_format($amount, 2) }}</td>
    </tr>
    <tr>
        <td>Date Generated</td>
        <td>{{ $plandate }}</td>
    </tr>
    <tr>
        <td>Status</td>
        <td>Credited ✓</td>
    </tr>
</table>

<p>Your account balance has been updated and the profits are available for withdrawal or reinvestment.</p>

<div class="text-center">
    <a href="{{ $settings->site_address }}/dashboard" class="button">View Portfolio</a>
</div>

<h2>Maximize Your Returns</h2>

<p>Want to grow your investment even more? Consider:</p>

<ul class="features-list">
    <li><strong>Reinvesting</strong> your profits to compound your earnings</li>
    <li><strong>Diversifying</strong> with additional trading bots</li>
    <li><strong>Withdrawing</strong> your profits securely</li>
</ul>

<div class="text-center">
    <a href="{{ $settings->site_address }}/user/trading-bots" class="button button-secondary">Manage Trading Bots</a>
</div>

<p>Keep up the great work! Our AI-powered trading bots continue to work 24/7 to grow your investment.</p>

<p style="margin-top: 30px;">Best regards,<br><strong>The {{ $settings->site_name }} Team</strong></p>

<div class="divider"></div>

<p class="text-muted" style="font-size: 13px;">This is an automated notification for returns generated by your trading bot. View detailed performance analytics in your dashboard.</p>
@endsection
